# Generated by Django 4.2.6 on 2023-10-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripton', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(upload_to='images/News', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Article_Name')),
                ('photo', models.ImageField(upload_to='images/Article', verbose_name='Photo')),
                ('description', models.TextField(max_length=1000000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_cat', to='application.category')),
            ],
        ),
    ]
